# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: development blog
email: michalsky@env.kiev.ua
description: > # this means to ignore newlines until "baseurl:"
  My name is Alex and this is my
  development blog.
baseurl: ""
url: "micha-sky.github.io" # the base hostname & protocol for your site
twitter_username: a_michalsky
github_username:  micha-sky

# Build settings
markdown: kramdown

excerpt_separator: "" 